# Generated by Django 4.0.5 on 2022-11-25 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Messages', 'verbose_name_plural': 'Message'},
        ),
    ]
